liquibase:
  change-log: classpath:liquibase/master.xml

spring:
  datasource:
    endpoint: jdbc:h2:file:./target/h2db/db/demodb;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true
  jackson:
    parser:
  profiles:
    active: live
gitter:
  api:
    endpoint: https://api.gitter.im/
    messages-resource: rooms/54f9e9a215522ed4b3dce824/chatMessages
    auth:
      token: 3cd4820adf59b6a7116f99d92f68a1b786895ce7
