liquibase:
  change-log: classpath:liquibase/master.xml

spring:
  datasource:
    url: jdbc:h2:file:./target/h2db/db/demodb;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true
  jackson:
    parser:
  profiles:
    active: live
  jpa:
    hibernate:
      ddl-auto: validate
gitter:
  api:
    endpoint: https://api.gitter.im/
    messages-resource: rooms/59ec60bcd73408ce4f7b21e9/chatMessages
    auth:
      token: ${GITTER_TOKEN}
