liquibase:
  change-log: classpath:liquibase/master.xml

spring:
  datasource:
    url: jdbc:h2:file:./target/h2db/db/demodb;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true
  jackson:
    parser:
  profiles:
    active: live