spring:
  liquibase:
    change-log: classpath:liquibase/master.xml
  datasource:
    url: jdbc:h2:file:./target/h2db/db/demodb;DB_CLOSE_DELAY=-1
  thymeleaf:
    reactive:
      max-chunk-size: 8192
  h2:
    console:
      enabled: true
  profiles:
    active: live
  jpa:
    hibernate:
      ddl-auto: validate
gitter:
  api:
    endpoint: https://stream.gitter.im/
    messages-resource: rooms/591ca8acd73408ce4f6049c1/chatMessages
    auth:
      token: ${GITTER_TOKEN}
