spring:
  profiles:
    active: live
  cloud:
    stream:
      default:
        producer:
          requiredGroups: messages

gitter:
  api:
    endpoint: https://api.gitter.im/
    messages-resource: rooms/59ec60bcd73408ce4f7b21e9/chatMessages
    auth:
      token: ${GITTER_TOKEN}
  stream:
    endpoint: https://stream.gitter.im/
    messages-resource: rooms/59ec60bcd73408ce4f7b21e9/chatMessages
    auth:
      token: ${GITTER_TOKEN}

server:
  port: 8081

