spring:
  profiles:
    active: live

gitter:
  api:
    endpoint: https://api.gitter.im/
    messages-resource: rooms/591ca8acd73408ce4f6049c1/chatMessages
    auth:
      token: ${GITTER_TOKEN}
  stream:
    endpoint: https://stream.gitter.im/
    messages-resource: rooms/591ca8acd73408ce4f6049c1/chatMessages
    auth:
      token: ${GITTER_TOKEN}

server:
  port: 8081
